/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIndexRouteImport } from './routes/editor.index'
import { Route as PreviewLoginRouteImport } from './routes/preview.login'
import { Route as EditorLoginRouteImport } from './routes/editor.login'
import { Route as EditorEmailRouteImport } from './routes/editor.email'
import { Route as EditorAccountRouteImport } from './routes/editor.account'
import { Route as PreviewAccountSplatRouteImport } from './routes/preview.account.$'

const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorRoute,
} as any)
const PreviewLoginRoute = PreviewLoginRouteImport.update({
  id: '/preview/login',
  path: '/preview/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorLoginRoute = EditorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => EditorRoute,
} as any)
const EditorEmailRoute = EditorEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => EditorRoute,
} as any)
const EditorAccountRoute = EditorAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => EditorRoute,
} as any)
const PreviewAccountSplatRoute = PreviewAccountSplatRouteImport.update({
  id: '/preview/account/$',
  path: '/preview/account/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteWithChildren
  '/editor/account': typeof EditorAccountRoute
  '/editor/email': typeof EditorEmailRoute
  '/editor/login': typeof EditorLoginRoute
  '/preview/login': typeof PreviewLoginRoute
  '/editor/': typeof EditorIndexRoute
  '/preview/account/$': typeof PreviewAccountSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor/account': typeof EditorAccountRoute
  '/editor/email': typeof EditorEmailRoute
  '/editor/login': typeof EditorLoginRoute
  '/preview/login': typeof PreviewLoginRoute
  '/editor': typeof EditorIndexRoute
  '/preview/account/$': typeof PreviewAccountSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteWithChildren
  '/editor/account': typeof EditorAccountRoute
  '/editor/email': typeof EditorEmailRoute
  '/editor/login': typeof EditorLoginRoute
  '/preview/login': typeof PreviewLoginRoute
  '/editor/': typeof EditorIndexRoute
  '/preview/account/$': typeof PreviewAccountSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/editor/account'
    | '/editor/email'
    | '/editor/login'
    | '/preview/login'
    | '/editor/'
    | '/preview/account/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor/account'
    | '/editor/email'
    | '/editor/login'
    | '/preview/login'
    | '/editor'
    | '/preview/account/$'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/editor/account'
    | '/editor/email'
    | '/editor/login'
    | '/preview/login'
    | '/editor/'
    | '/preview/account/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRouteWithChildren
  PreviewLoginRoute: typeof PreviewLoginRoute
  PreviewAccountSplatRoute: typeof PreviewAccountSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof EditorRoute
    }
    '/preview/login': {
      id: '/preview/login'
      path: '/preview/login'
      fullPath: '/preview/login'
      preLoaderRoute: typeof PreviewLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/login': {
      id: '/editor/login'
      path: '/login'
      fullPath: '/editor/login'
      preLoaderRoute: typeof EditorLoginRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/email': {
      id: '/editor/email'
      path: '/email'
      fullPath: '/editor/email'
      preLoaderRoute: typeof EditorEmailRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/account': {
      id: '/editor/account'
      path: '/account'
      fullPath: '/editor/account'
      preLoaderRoute: typeof EditorAccountRouteImport
      parentRoute: typeof EditorRoute
    }
    '/preview/account/$': {
      id: '/preview/account/$'
      path: '/preview/account/$'
      fullPath: '/preview/account/$'
      preLoaderRoute: typeof PreviewAccountSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EditorRouteChildren {
  EditorAccountRoute: typeof EditorAccountRoute
  EditorEmailRoute: typeof EditorEmailRoute
  EditorLoginRoute: typeof EditorLoginRoute
  EditorIndexRoute: typeof EditorIndexRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorAccountRoute: EditorAccountRoute,
  EditorEmailRoute: EditorEmailRoute,
  EditorLoginRoute: EditorLoginRoute,
  EditorIndexRoute: EditorIndexRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRouteWithChildren,
  PreviewLoginRoute: PreviewLoginRoute,
  PreviewAccountSplatRoute: PreviewAccountSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
